// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createHttpsFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase@0.0.0-test",
  "id": "fetch-info-js",
  "name": "/api/fetch-info",
  "version": "4591b6e1af3dde46ddfd1acfad122831dfe206f9ed822dc319a9450c1ac47bca"
}
const CONFIG = {}

module.exports = createHttpsFunction(require('../../.cache/functions/fetch-info.js'), METADATA, CONFIG)
