// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createHttpsFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase@0.0.0-test",
  "id": "hello-world-js",
  "name": "/api/hello-world",
  "version": "86a14a597e1c2ab950876b7284432be2f559b8d56aac83da89115f6682e79ac3"
}
const CONFIG = {}

module.exports = createHttpsFunction(require('../../.cache/functions/hello-world.js'), METADATA, CONFIG)
