// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createHttpsFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase@0.0.0-test",
  "id": "ssr-engine",
  "name": "SSR",
  "version": "056471d80bf5b0b200ad13358e43d6b5f9d07b1634c5d9dd50e006a8593feefb"
}
const CONFIG = {
  "region": "asia-northeast1",
  "timeoutSeconds": 120
}

module.exports = createHttpsFunction(require('../../.cache/page-ssr/lambda.js'), METADATA, CONFIG)
