// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createHttpsFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase",
  "id": "ssr-engine",
  "name": "SSR",
  "version": "dbddfdd9f69dfa72c82263182ff1d4ad50993e212b46cb3ed303d4b55568b295"
}
const CONFIG = {
  "region": "asia-northeast1",
  "timeoutSeconds": 120
}

module.exports = createHttpsFunction(require('../../.cache/page-ssr/lambda.js'), METADATA, CONFIG)
