// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createCachedHttpsFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase@0.0.0-test",
  "id": "ssr-engine-cached",
  "name": "DSG",
  "version": "916bd438101b7db36b63b5e02832024cca2fe21353db7bef6bf97638d826ad6c"
}
const CONFIG = {}

module.exports = createCachedHttpsFunction(require('../../.cache/page-ssr/lambda.js'), METADATA, CONFIG)
