// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createHttpsFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase@0.0.0-test",
  "id": "test-fetch-info-js",
  "name": "/api/test/fetch-info",
  "version": "db42005d13f75b8b08e339173d9885d9b7b6ae8cb3711c00b528464f27fd0db2"
}
const CONFIG = {}

module.exports = createHttpsFunction(require('../../.cache/functions/test/fetch-info.js'), METADATA, CONFIG)
