// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createHttpsFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase",
  "id": "test-fetch-info-js",
  "name": "/api/test/fetch-info",
  "version": "66e6d96e471f7f3130b0b5b32bea687aa812ca0391e8dddfe118dc0e62aaf308"
}
const CONFIG = {}

module.exports = createHttpsFunction(require('../../.cache/functions/test/fetch-info.js'), METADATA, CONFIG)
