// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createHttpsFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase",
  "id": "fetch-info-js",
  "name": "/api/fetch-info",
  "storageBucket": "test-project.appspot.com",
  "version": "ab80e6602321ea537397c732efec810759a621f9ef78bf401ace158c3d506004"
}
const CONFIG = {
  "labels": {
    "custom": "custom-label"
  }
}

module.exports = createHttpsFunction(require('../../.cache/functions/fetch-info.js'), METADATA, CONFIG)
