// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase",
  "id": "fetch-info-js",
  "name": "/api/fetch-info",
  "storageBucket": "test-project.appspot.com",
  "version": "8148dc0f2ff4d1ced85bd3836cb4e44d627b9f176c6854f5f09e6783fcb31d47"
}
const CONFIG = {
  "labels": {
    "custom": "custom-label"
  }
}

module.exports = createFunction(require('../../.cache/functions/fetch-info.js'), METADATA, CONFIG)
