// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase",
  "id": "hello-world-js",
  "name": "/api/hello-world",
  "storageBucket": "test-project.appspot.com",
  "version": "a3d956c6f29f80497a0544469a69ae9499eaa1c3cb86cebe39f33910e65fa674"
}
const CONFIG = {
  "labels": {
    "custom": "custom-label"
  }
}

module.exports = createFunction(require('../../.cache/functions/hello-world.js'), METADATA, CONFIG)
