// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createHttpsFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase",
  "id": "hello-world-js",
  "name": "/api/hello-world",
  "storageBucket": "test-project.appspot.com",
  "version": "305d53201f0c594a4fd56bc6bf83217d26185d4061ca261086c65ae88be13768"
}
const CONFIG = {
  "labels": {
    "custom": "custom-label"
  }
}

module.exports = createHttpsFunction(require('../../.cache/functions/hello-world.js'), METADATA, CONFIG)
