// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase",
  "id": "ssr-engine",
  "name": "SSR",
  "storageBucket": "test-project.appspot.com",
  "version": "c003a1f84b4301e1dba195a75d9a3fe4d5d1b3ff1263802e2d16cb87b5e27de9"
}
const CONFIG = {
  "labels": {
    "custom": "custom-label"
  },
  "region": "asia-northeast1",
  "timeoutSeconds": 120
}

module.exports = createFunction(require('../../.cache/page-ssr/lambda.js'), METADATA, CONFIG)
