// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createCachedFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase",
  "id": "ssr-engine-cached",
  "name": "DSG",
  "storageBucket": "test-project.appspot.com",
  "version": "dfaba89beec5d5c659416ffd93eff6151001a2018063221fe49663b9cea2689e"
}
const CONFIG = {
  "labels": {
    "custom": "custom-label"
  }
}

module.exports = createCachedFunction(require('../../.cache/page-ssr/lambda.js'), METADATA, CONFIG)
