// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createCachedHttpsFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase",
  "id": "ssr-engine-cached",
  "name": "DSG",
  "storageBucket": "test-project.appspot.com",
  "version": "18b014f61236243f7ab6f7d77386e71d17f27fa8b2e8b1ef7db3e7f8fcbc3275"
}
const CONFIG = {
  "labels": {
    "custom": "custom-label"
  }
}

module.exports = createCachedHttpsFunction(require('../../.cache/page-ssr/lambda.js'), METADATA, CONFIG)
