// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase",
  "id": "test-fetch-info-js",
  "name": "/api/test/fetch-info",
  "storageBucket": "test-project.appspot.com",
  "version": "b4dc821ad1720fbfde273634f6c3ae7b7c00c7b58bb0a7612ce5f32241f366ce"
}
const CONFIG = {
  "labels": {
    "custom": "custom-label"
  }
}

module.exports = createFunction(require('../../.cache/functions/test/fetch-info.js'), METADATA, CONFIG)
