// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createHttpsFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase",
  "id": "ssr-engine",
  "name": "SSR",
  "storageBucket": "test-project.appspot.com",
  "version": "f28ad437b47b9f49b28445a02d3fdb7e0341cbfa22db2a875dcc429dab425226"
}
const CONFIG = {
  "labels": {
    "custom": "custom-label"
  },
  "region": "asia-northeast1",
  "timeoutSeconds": 120
}

module.exports = createHttpsFunction(require('../../.cache/page-ssr/lambda.js'), METADATA, CONFIG)
