// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createHttpsFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase",
  "id": "test-fetch-info-js",
  "name": "/api/test/fetch-info",
  "storageBucket": "test-project.appspot.com",
  "version": "a97d562d20595c9755cc34c6ca50539c7053666ccc58e8c34f264290100b9df5"
}
const CONFIG = {
  "labels": {
    "custom": "custom-label"
  }
}

module.exports = createHttpsFunction(require('../../.cache/functions/test/fetch-info.js'), METADATA, CONFIG)
