// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase",
  "id": "fetch-info-js",
  "name": "/api/fetch-info",
  "version": "6bc77a9aa4b331495a544f670bb4089da5adb02f51784bdadd8ad2975d73a8cf"
}
const CONFIG = {}

module.exports = createFunction(require('../../.cache/functions/fetch-info.js'), METADATA, CONFIG)
