// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createHttpsFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase",
  "id": "fetch-info-js",
  "name": "/api/fetch-info",
  "version": "efc1889f917c17e93ed8c5f22e72a05a2286f4090fd6eed1cf960f733f95be1a"
}
const CONFIG = {}

module.exports = createHttpsFunction(require('../../.cache/functions/fetch-info.js'), METADATA, CONFIG)
