// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase",
  "id": "hello-world-js",
  "name": "/api/hello-world",
  "version": "3ddcb882a7a325e4d51d1875e05304df7e685d02a42b309ccf572fe8e79f6ef5"
}
const CONFIG = {}

module.exports = createFunction(require('../../.cache/functions/hello-world.js'), METADATA, CONFIG)
