// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createHttpsFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase",
  "id": "hello-world-js",
  "name": "/api/hello-world",
  "version": "b05aa9320ddbab9faaf3781cbe7357ba1136338c09ae857b6c496b1cdb84e433"
}
const CONFIG = {}

module.exports = createHttpsFunction(require('../../.cache/functions/hello-world.js'), METADATA, CONFIG)
