// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase",
  "id": "ssr-engine",
  "name": "SSR",
  "version": "904a020b4d83a9fe575b42327411150ba3b0725c3262ff4386e6a6438083df39"
}
const CONFIG = {}

module.exports = createFunction(require('../../.cache/page-ssr/lambda.js'), METADATA, CONFIG)
