// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createCachedHttpsFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase",
  "id": "ssr-engine-cached",
  "name": "DSG",
  "version": "b30af107251e9cff9edd8626c78be7840b16db0ba6faadbdc3fed4a961adbff5"
}
const CONFIG = {}

module.exports = createCachedHttpsFunction(require('../../.cache/page-ssr/lambda.js'), METADATA, CONFIG)
