// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createHttpsFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase",
  "id": "ssr-engine",
  "name": "SSR",
  "version": "243f9fa29cfcde30937e8ae01801c468e6bb097c81d3d698773c43eb21d4697a"
}
const CONFIG = {}

module.exports = createHttpsFunction(require('../../.cache/page-ssr/lambda.js'), METADATA, CONFIG)
