// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createCachedFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase",
  "id": "ssr-engine-cached",
  "name": "DSG",
  "version": "d2f4dee7eea3453f865ba1f4b74d88e52426ac48d298c41b079fa2c11089ddc8"
}
const CONFIG = {}

module.exports = createCachedFunction(require('../../.cache/page-ssr/lambda.js'), METADATA, CONFIG)
