// Auto-generated by gatsby-adapter-firebase. Do not edit.
'use strict'

const { createFunction } = require('../runtime.cjs')

const METADATA = {
  "generator": "gatsby-adapter-firebase",
  "id": "test-fetch-info-js",
  "name": "/api/test/fetch-info",
  "version": "c7b3af4b6323902d344712e651e28f6d20a3bbf6da1bb108509c9739b6605cee"
}
const CONFIG = {}

module.exports = createFunction(require('../../.cache/functions/test/fetch-info.js'), METADATA, CONFIG)
