- title: Home
  routes:
    home: /
  template: home.js
- title: Blog
  routes:
    blog: /blog
    blog.tag: /blog/tag/:tag
  template: blog.js
  helper: blog.js
- title: Blog Post
  routes:
    blog.post: /blog/:post
  template: post.js
  helper: blog.js
