name: Deploy Demo

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: demo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        with:
          version: 10
          run_install: false

      - name: Set up Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: demo/package-lock.json

      - name: Build adaptor
        run: pnpm install
        working-directory: ./

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Authenticate Firebase CLI
        run: |
          echo "${FIREBASE_SERVICE_ACCOUNT}" > "${HOME}/gcp-key.json"
          echo "GOOGLE_APPLICATION_CREDENTIALS=${HOME}/gcp-key.json" >> $GITHUB_ENV
          npm install -g firebase-tools
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_GATSBY_FIREBASE_87451 }}

      - name: Deploy to Firebase
        run: firebase --project gatsby-firebase-87451 deploy
